token = "NzE1MTMwODExMTU4MTAyMDQ4.Xs4vvQ.TlTOSYMM8_BeUFdI7AO8fwpVE7w"
welcome_channel = "715063178031005767"
log_channel = "715413775750004766"
admin_channel = "715183992688607292"
admin_log_channel = "987654321"
admin_role_id = "715063252304003082"
supermod_role_id = "715188166293979196"
mod_role_id = "715188120626135301"
user_role_id = "715063417852919868"
welcome_message = "Assalam Alikum\nWelcome to the server, %s! In order to get full access to the server, you have to Read the #rules and Answer the following questions: \n1. \n2. \n3. \n If you need any help, just @ moderators and they will help you."
command_prefix = ";"

[[role]]
  id = "1235435345476"
  name = "cool_kid"
  description = "self-assignable role with the name 'cool_kid'"

[[role]]
  id = "7656535438"
  name = "developer"
  description = "self-assignable roles for developers"
