token = "NzE1MTMwODExMTU4MTAyMDQ4.GEUXBw.hn6mGI8_nGJU1BBx8Ib1MzqyvrEEOvVJSFrR1Y"
qlc_server_id = "678795606906634281"
welcome_channel = "714908405969453178"
log_channel = "726666813529915463"
admin_channel = "715788916132937728"
bot_channel = "710648266790010970"
rules_channel = "679065466173390910"
staff_channel = "703160352157859840"
approval_and_verification = "716344777100230767"
admin_log_channel = "715788890744684585"
archive_channel = "725956709188763758"
admin_role_id = "714905000668692541"
server_booster_id = "719349234977210389"
supermod_role_id = "716343534126628944"
mod_role_id = "700866384044752936"
trial_mod_rol_id = "739011082319954011"
voice_verify_sisters_rol_id = "1023117275034812466"
voice_verify_brothers_rol_id = "917740028665405500"
user_role_id = "680170954432839798"
female_only_role_id = "762131543840915469"
circle_leader_role_id = "741712009057402992"
Omer_Ibn_Al_Khattab_Circle_id = "745126057300066344"
abu_bakar_alsiddeeq_circle_id = "745126425702694972"
ali_bin_abi_talib_id = "745125831415693374"
sisters_circle_id = "745125488237740082"
brothers_helper_role_id = "714905012798750870"
sisters_helper_role_id = "714941314768044169"
male_role_id = "680388374124822577"
female_role_id = "680388518882836509"
verified_male_role_id = "719618009731170344"
verified_female_role_id = "719618129319297064"
muted_role_id = "709449969660067911"
isolated_role_id = "867232111273181185"
welcome_message = "‎السلام عليكم ورحمة الله وبركاته \nMay the peace, mercy and blessings of Allah be upon you.\n\n Welcome %s :star2: to the Quran Learning Center.\n\n**This server is dedicated to:**\n • The memorization and recitation of the Quran\n • Learning Tajweed and Arabic\n\n**Please read the <#%s> and answer the following questions to proceed:**\n1. What is your gender (Male or Female)?\n2. How much of the Quran do you know/memorize?\n3. What is your reason for joining (plus anything else you’d like to share)?\n\n*Note: we may ask extra questions.*\n\n__If you need any help or have any questions, feel free to ask here and tag__ `@Moderator`.\n\nJazakumullahu khayran\nWe hope that you benefit from the server."
approval_message = "Welcome %s to the server and thank you for joining :blush:\n\n:small_blue_diamond: To view all the roles, type: `;role list` (in <#%s>)\n:small_blue_diamond: To get a role, type: `;role get ......`\n:small_blue_diamond: To view Tajweed lessons, type:`;lessons`\n:small_blue_diamond: To view Arabic lessons, type: `;arabiclesson` \n:small_blue_diamond: To set your time zone, type: `-ft set @YourUsername` then the timezone region (e.g. California/United States).\n\n:small_orange_diamond: For resources view #tajweed-resources and #arabic-resources.\n:small_orange_diamond: For Tajweed help: tag a `@Tajweed Helper` \n:small_orange_diamond: For Qur’an help and testing: `@Brothers Helper` or `@Sisters Helper`. \n:small_orange_diamond: Gender specific channels: require verification, tag a `@Moderator` for more information. \n:small_orange_diamond: To join a Hifdh Circle: be verified and tag a `@Super Moderator` for more information. If you have any questions or need any help, please do not hesitate to ask."
command_prefix = ";"


banned_words = [ "nudes", "asshole","biatch", "Scumbag","pain in the ass", "blowjob", "blow job", "buttplug", "orgasm","cunt", "dildo", " fagget", "faggot", " penis", "scrotum", "slut", "vagina", "whore", "fellatio", "f u c k", "clitoris", "fuck", "fuckin","mother fucker","motherfucker", "suck my dick", "f*ck", "f**k", "bitch", "negro", "nigger", "nigga","n**ger", "n*gga","n**ga"]

[[rule]]
  number = "1"
  text = "Be respectful. Do not insult/mock anyone at all, nor harass or bother them."

[[rule]]
  number = "2"
  text = "Do not use inappropriate or vulgar language or anything that may offend someone."

  [[rule]]
  number = "3"
  text = "Do not share any sensitive or private information of yourself or anyone."


  [[rule]]
  number = "4"
  text = "Your posts, links, profiles should not contain NSFW, awrah, any offensive content or spam. Do not send anything that might harm a member (e.g. medically), scare them, or cause fitnah."

  [[rule]]
  number = "5"
  text = "Do not scam or send any harmful links or IP grabbers."

  [[rule]]
  number = "6"
  text = "Do not advertise on the server or send discord invites without permission."

  [[rule]]
  number = "7"
  text = "Send messages in the appropriate channels. (Read channel topics before chatting)."

  [[rule]]
  number = "8"
  text = "Give a music warning before posting content that contains music."

  [[rule]]
  number = "9"
  text = "Do not join with an alt account (if you wish to switch accounts tell us)."

  [[rule]]
  number = "10"
  text = "Do not tag moderators, helpers or members without a proper reason or excessively. Additionally, leave a 1.5 hour gap between pinging the Recite Together role."

  [[rule]]
  number = "11"
  text = "Any gender-exclusive discussion or conversations regarding marriage should be in the gender-exclusive channels. (Get verified to access those!)."

  [[rule]]
  number = "12"
  text = "We follow the Qur'an, the authentic Sunnah and the Salaf. Do not spread anything opposing this or argue regarding it."

  [[rule]]
  number = "13"
  text = "Do not speak without knowledge, and always be sure to fact check anything you send. Do not send or say anything misleading or untruthful, and do not be extreme!"

  [[rule]]
  number = "14"
  text = "Do not debate/argue or converse in a way that might incite an argument. (E.g. politics, extremist groups, sects, deviant aqeedah, etc.)."

  [[rule]]
  number = "15"
  text = "Communicate with the opposite gender appropriately."

 [[rule]]
  number = "16"
  text = "If the moderators ask you to do something then comply."





[[role]]
  id = "714905000748515338"
  name = "tajweedlesson1"
  description = "A self-assignable role for those who wish to be reminded of the tajweed lesson session 1"

  [[role]]
  id = "714905008382017640"
  name = "tajweedlesson2"
  description = "A self-assignable role for those who wish to be reminded of the tajweed lesson session 2"


  
 [[role]]
  id = "727701054128390165"
  name = "arabiclesson"
  description = "A self-assignable role for those who wish to be reminded of the intermediate-level Arabic lesson"

 [[role]]
  id = "857652617487974410"
  name = "beginnerarabic"
  description = "A self-assignable role for those who wish to be reminded of the Arabic lesson for beginners"


[[role]]
  id = "882291323724525618"
  name = "tafsirclass"
  description = "A self-assignable role for those who wish to be reminded of the Tafsir Class"

[[role]]
  id = "897199822644342825"
  name = "Introtoislam"
  description = "A self-assignable role for those who wish to be reminded of the Introduction to Islam Class"


[[role]]
  id = "897200019122302986"
  name = "Usul"
  description = "A self-assignable role for those who wish to be reminded of Usul Al Fiqh Class"

  [[role]]
  id = "727340877072171048"
  name = "recitetogether"
  description = "A self-assignable role for those who want to recite together in the voice chat or listen to others recite."

 [[role]]
  id = "897829906711478394"
  name = "femalerecitetogether"
  description = "A self-assignable role for female members who want to recite together in the female voice chat or listen to others recite."


  [[role]]
  id = "727349233921032212"
  name = "events"
  description = "A self-assignable role for those who want to be notified about new events such as Quran quizzes, Islamic Quzzies, lectures, etc."

 [[role]]
  id = "830463604850819122"
  name = "khatma"
  description = "A self-assignable role for those who want to be notified about the daily recitation during the holy month of Ramadhan."

 [[role]]
  id = "830463850238836737"
  name = "khatmafemale"
  description = "A self-assignable role for those who want to be notified about about the daily recitation during the holy month of Ramadhan for female members."



   [[role]]
  id = "722098745386205274"
  name = "English"
  description = "A self-assignable role for those who speak English"

   [[role]]
  id = "722098817507524678"
  name = "Arabic"
  description = "A self-assignable role for those who speak Arabic"

  [[role]]
  id = "722098858288480267"
  name = "Japanese"
  description = "A self-assignable role for those who speak Japanese"

  [[role]]
  id = "916009197970288651"
  name = "Korean"
  description = "A self-assignable role for those who speak Korean"

  [[role]]
  id = "722098887854391306"
  name = "French"
  description = "A self-assignable role for those who speak French"

  [[role]]
  id = "722098945446248490"
  name = "Chinese"
  description = "A self-assignable role for those who speak Chinese"

  [[role]]
  id = "722098919684702218"
  name = "Urdu"
  description = "A self-assignable role for those who speak Urdu"

  [[role]]
  id = "722099260006334526"
  name = "Spanish"
  description = "A self-assignable role for those who speak Spanish"

  [[role]]
  id = "722099379779010610"
  name = "Norwegian"
  description = "A self-assignable role for those who speak Norwegian"

 [[role]]
  id = "863382477182861332"
  name = "Danish"
  description = "A self-assignable role for those who speak Danish"


  [[role]]
  id = "722098976882688052"
  name = "Indonesian"
  description = "A self-assignable role for those who speak Indonesian"

  
  [[role]]
  id = "723189855202574418"
  name = "Malay"
  description = "A self-assignable role for those who speak Malay"

  
  [[role]]
  id = "725177215935053855"
  name = "Dutch"
  description = "A self-assignable role for those who speak Dutch"

  
  [[role]]
  id = "725180041859956829"
  name = "Somali"
  description = "A self-assignable role for those who speak Somali"


[[role]]
  id = "725183251186057257"
  name = "Swedish"
  description = "A self-assignable role for those who speak Swedish"


[[role]]
  id = "725183280340795392"
  name = "Turkish"
  description = "A self-assignable role for those who speak Turkish"

[[role]]
  id = "725186911018418287"
  name = "Finnish"
  description = "A self-assignable role for those who speak Finnish"

  [[role]]
  id = "725228341036187718"
  name = "Bangla"
  description = "A self-assignable role for those who speak Bangla"

   [[role]]
  id = "726013417923543080"
  name = "Macedonian"
  description = "A self-assignable role for those who speak Macedonian"

   [[role]]
  id = "726013655451303936"
  name = "Bosnian"
  description = "A self-assignable role for those who speak Bosnian"

   [[role]]
  id = "726024240586817577"
  name = "Albanian"
  description = "A self-assignable role for those who speak Albanian"

  
     [[role]]
  id = "728586902588096542"
  name = "Kurdish"
  description = "A self-assignable role for those who speak Kurdish"

    [[role]]
  id = "728814577478795271"
  name = "German"
  description = "A self-assignable role for those who speak German"

  
    [[role]]
  id = "729035923605684267"
  name = "Hebrew"
  description = "A self-assignable role for those who speak Hebrew"

  

   [[role]]
  id = "732125349789565048"
  name = "Portuguese"
  description = "A self-assignable role for those who speak Portuguese"

     [[role]]
  id = "738477337934430239"
  name = "Tamazight"
  description = "A self-assignable role for those who speak Tamazight"

   [[role]]
  id = "739391683074064484"
  name = "Swahili"
  description = "A self-assignable role for those who speak Swahili"

  
    [[role]]
  id = "743399964251783189"
  name = "Hindi"
  description = "A self-assignable role for those who speak Hindi"

   [[role]]
  id = "743918521372770404"
  name = "Italian"
  description = "A self-assignable role for those who speak Italian"

   [[role]]
  id = "783730718101864509"
  name = "Persian"
  description = "A self-assignable role for those who speak Persian"


    [[role]]
  id = "854702321110614027"
  name = "Latvian"
  description = "A self-assignable role for those who speak Latvian"


      [[role]]
  id = "874608546585673768"
  name = "Lithuanian"
  description = "A self-assignable role for those who speak Lithuanian"

        [[role]]
  id = "907343997431853087"
  name = "Tagalog"
  description = "A self-assignable role for those who speak Tagalog"


        [[role]]
  id = "914199727938084864"
  name = "Dhivehi"
  description = "A self-assignable role for those who speak Dhivehi"
  