token = "NzE1MTMwODExMTU4MTAyMDQ4.Xs4vdw.jZWjFKk5npVZcESEsHRHimHvWoQ"
welcome_channel = "714908405969453178"
log_channel = "726666813529915463"
admin_channel = "715788916132937728"
bot_channel = "710648266790010970"
rules_channel = "679065466173390910"
staff_channel = "703160352157859840"
approval_and_verification = "716344777100230767"
admin_log_channel = "715788890744684585"
archive_channel = "725956709188763758"
admin_role_id = "714905000668692541"
server_booster_id = "719349234977210389"
supermod_role_id = "716343534126628944"
mod_role_id = "700866384044752936"
trial_mod_rol_id = "739011082319954011"
user_role_id = "680170954432839798"
circle_leader_role_id = "741712009057402992"
Omer_Ibn_Al_Khattab_Circle_id = "745126057300066344"
abu_bakar_alsiddeeq_circle_id = "745126425702694972"
ali_bin_abi_talib_id = "745125831415693374"
sisters_circle_id = "745125488237740082"
brothers_helper_role_id = "714905012798750870"
sisters_helper_role_id = "714941314768044169"
male_role_id = "680388374124822577"
female_role_id = "680388518882836509"
verified_male_role_id = "719618009731170344"
verified_female_role_id = "719618129319297064"
muted_role_id = "709449969660067911"

welcome_message = "السلام عليكم ورحمة اللّٰه وبركاته\nMay peace and mercy of Allah be upon you \n\nWelcome %s to the Quran Learning Center, a server dedicated to aiding its members in the memorization and recitation of the Quran, including teaching Tajweed. We hope that you benefit from this server and what it has to offer. In order to have full access to the server, You have to read the Rules in <#%s> and we kindly request that you inform us of: \n1. **Your gender (Male or Female)** \n2. **how much of the Quran do you know/memorize?** \n3. **The reason for joining the server plus anything else you would like to share.**\n\nAfter completing these steps, a Moderator will grant you approval inshallah.\nIf you need any help or have any questions, feel free to ask here and tag @ Moderators.\nJazakum Allah Khair\n\nAnd May Allah protect you and guide you to the straight path."
approval_message = "You now have full access to the server %s!. Use `;help` for guidance on using the bot for this server.\n\n If you need help with Quran memorization (recite to others any they correct you), feel free to ask one of the  helpers by tagging @ brothers helper or @ sisters helper at any time. \n\n If you need help with your tajweed, feel free to ask one of the tajweed helpers by tagging @ tajweed helpers at any time. \n\nIf you wish to access the gender specific channels, your gender must be verified by a Moderator in the voice chat. If you like to do that now, feel free to jump into Gender Verification VC and a Moderator will join you shortly. You can also do that later if you like.\n\nMay Allah help you with all your endeavors."

command_prefix = ";"


banned_words = [ "nudes", "asshole","biatch", "Scumbag","pain in the ass", "blowjob", "blow job", "buttplug", "orgasm","cunt", "dildo", " fagget", "faggot", " penis", "scrotum", "slut", "vagina", "whore", "fellatio", "f u c k", "clitoris", "fuck", "fuckin","mother fucker","motherfucker", "suck my dick", "f*ck", "f**k", "bitch", "negro", "nigger", "nigga","n**ger", "n*gga","n**ga"]



  
 [[role]]
  id = "727701054128390165"
  name = "arabiclesson"
  description = "A self-assignable role for those who wish to be reminded of the Arabic lesson"


  [[role]]
  id = "727340877072171048"
  name = "recitetogether"
  description = "A self-assignable role for those who want to recite together in the voice chat or listen to others recite."

  [[role]]
  id = "727349233921032212"
  name = "events"
  description = "A self-assignable role for those who want to be notified about new events such as Quran quizzes, Islamic Quzzies, lectures, etc."

 [[role]]
  id = "830463604850819122"
  name = "khatma"
  description = "A self-assignable role for those who want to be notified about the daily recitation during the holy month of Ramadhan."

 [[role]]
  id = "830463850238836737"
  name = "khatmafemale"
  description = "A self-assignable role for those who want to be notified about about the daily recitation during the holy month of Ramadhan for female members."



   [[role]]
  id = "722098745386205274"
  name = "English"
  description = "A self-assignable role for those who speak English"

   [[role]]
  id = "722098817507524678"
  name = "Arabic"
  description = "A self-assignable role for those who speak Arabic"

  [[role]]
  id = "722098858288480267"
  name = "Japanese"
  description = "A self-assignable role for those who speak Japanese"

  [[role]]
  id = "722098887854391306"
  name = "French"
  description = "A self-assignable role for those who speak French"

  [[role]]
  id = "722098945446248490"
  name = "Chinese"
  description = "A self-assignable role for those who speak Chinese"

  [[role]]
  id = "722098919684702218"
  name = "Urdu"
  description = "A self-assignable role for those who speak Urdu"

  [[role]]
  id = "722099260006334526"
  name = "Spanish"
  description = "A self-assignable role for those who speak Spanish"

  [[role]]
  id = "722099379779010610"
  name = "Norwegian"
  description = "A self-assignable role for those who speak Norwegian"

  [[role]]
  id = "722098976882688052"
  name = "Indonesian"
  description = "A self-assignable role for those who speak Indonesian"

  
  [[role]]
  id = "723189855202574418"
  name = "Malay"
  description = "A self-assignable role for those who speak Malay"

  
  [[role]]
  id = "725177215935053855"
  name = "Dutch"
  description = "A self-assignable role for those who speak Dutch"

  
  [[role]]
  id = "725180041859956829"
  name = "Somali"
  description = "A self-assignable role for those who speak Somali"


[[role]]
  id = "725183251186057257"
  name = "Swedish"
  description = "A self-assignable role for those who speak Swedish"


[[role]]
  id = "725183280340795392"
  name = "Turkish"
  description = "A self-assignable role for those who speak Turkish"

[[role]]
  id = "725186911018418287"
  name = "Finnish"
  description = "A self-assignable role for those who speak Finnish"

  [[role]]
  id = "725228341036187718"
  name = "Bangla"
  description = "A self-assignable role for those who speak Bangla"

   [[role]]
  id = "726013417923543080"
  name = "Macedonian"
  description = "A self-assignable role for those who speak Macedonian"

   [[role]]
  id = "726013655451303936"
  name = "Bosnian"
  description = "A self-assignable role for those who speak Bosnian"

   [[role]]
  id = "726024240586817577"
  name = "Albanian"
  description = "A self-assignable role for those who speak Albanian"

  
     [[role]]
  id = "728586902588096542"
  name = "Kurdish"
  description = "A self-assignable role for those who speak Kurdish"

    [[role]]
  id = "728814577478795271"
  name = "German"
  description = "A self-assignable role for those who speak German"

  
    [[role]]
  id = "729035923605684267"
  name = "Hebrew"
  description = "A self-assignable role for those who speak Hebrew"

  

   [[role]]
  id = "732125349789565048"
  name = "Portuguese"
  description = "A self-assignable role for those who speak Portuguese"

     [[role]]
  id = "738477337934430239"
  name = "Tamazight"
  description = "A self-assignable role for those who speak Tamazight"

       [[role]]
  id = "739391683074064484"
  name = "Swahili"
  description = "A self-assignable role for those who speak Swahili"

  
       [[role]]
  id = "743399964251783189"
  name = "Hindi"
  description = "A self-assignable role for those who speak Hindi"

         [[role]]
  id = "743918521372770404"
  name = "Italian"
  description = "A self-assignable role for those who speak Italian"

           [[role]]
  id = "783730718101864509"
  name = "Persian"
  description = "A self-assignable role for those who speak Persian"