---

- name: Deploy Ifreet
  hosts: all
  tasks:

    - name: Deploy new executable
      copy:
        src: ../ifreet
        dest: ifreet/{{ ENVIRONMENT }}/
        mode: u+x

    - name: Create config if missing
      template:
        src: config.toml.j2
        dest: ifreet/{{ ENVIRONMENT }}/config.toml
        force: no

    - name: Create unit file
      template:
        src: ifreet.service
        dest: .config/systemd/user/ifreet-{{ ENVIRONMENT }}.service

    - name: Restart service
      systemd:
        name: ifreet-{{ ENVIRONMENT }}
        state: restarted
        scope: user
